"use client";
import {useEffect,useMemo,useState} from 'react';
import {Globe2,Search,SlidersHorizontal,FileText,MapPin,Clock3,BriefcaseBusiness,ExternalLink,Upload,ShieldCheck,Trash2,RefreshCw,Check,Database,ChartNoAxesCombined} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Checkbox} from '@/components/ui/checkbox';
import {initialFilters,filterJobs,matchJob,extractSkills,salaryLabel,safeLink,type Job,type Profile,type Filters} from '@/lib/jobs';
import {readDocuments,saveDocument,deleteDocument,parseDocument} from '@/lib/profile-store';
import CostView from './cost-view';

function Pick({label,value,onChange,options}:{label:string;value:string;onChange:(s:string)=>void;options:string[]}){return <label className="field"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o} value={o}>{o==='all'?'Any':o}</SelectItem>)}</SelectContent></Select></label>;}
const fmt=(n:number|undefined)=>(n??0).toLocaleString();
const when=(s:string|undefined)=>s?new Date(s).toLocaleString():'Not yet collected';
export default function RemoteAtlas(){
 const [jobs,setJobs]=useState<Job[]>([]),[stats,setStats]=useState<any>(null),[coverage,setCoverage]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [filters,setFilters]=useState<Filters>(initialFilters),[tab,setTab]=useState('jobs'),[selected,setSelected]=useState<Job|null>(null),[page,setPage]=useState(1),[profile,setProfile]=useState<Profile[]>([]),[sort,setSort]=useState('Newest'),[busy,setBusy]=useState(''),[message,setMessage]=useState(''),[companySearch,setCompanySearch]=useState(''),[companyState,setCompanyState]=useState('all'),[pasted,setPasted]=useState('');
 async function load(){setLoading(true);setError('');try{const r=await Promise.all(['jobs','stats','coverage'].map(async name=>{const res=await fetch(`./data/${name}.json`,{cache:'no-store'});if(!res.ok)throw new Error('The job catalog is unavailable. Please retry.');return res.json();}));setJobs(r[0] as Job[]);setStats(r[1]);setCoverage(r[2] as any[]);}catch(e){setError(e instanceof Error?e.message:'Unable to load jobs.');}finally{setLoading(false);}}
 useEffect(()=>{load();readDocuments().then(setProfile).catch(()=>setMessage('Private storage is unavailable in this browser.'));},[]);
 useEffect(()=>setPage(1),[filters,sort]);
 const matched=useMemo(()=>new Map(jobs.map(j=>[j.id,matchJob(j,profile)])),[jobs,profile]);
 const results=useMemo(()=>filterJobs(jobs,filters).sort((a,b)=>sort==='Best match'?(matched.get(b.id)?.score??0)-(matched.get(a.id)?.score??0):Date.parse(b.firstSeen)-Date.parse(a.firstSeen)),[jobs,filters,sort,matched]);
 const industries=useMemo(()=>['all',...Array.from(new Set(jobs.map(j=>j.industry))).sort()],[jobs]);
 const skills=extractSkills(profile.map(p=>p.text).join('\n'));
 function change(k:keyof Filters,v:any){setFilters(f=>({...f,[k]:v}));}
 async function upload(file:File|undefined,kind:'resume'|'cover'){if(!file)return;setBusy(kind);setMessage('');try{const text=await parseDocument(file);await saveDocument({id:kind,kind,name:file.name,text,uploadedAt:new Date().toISOString(),file});setProfile(await readDocuments());setMessage('Saved privately on this device. Your matches are updated.');}catch(e){setMessage(e instanceof Error?e.message:'Upload failed. Your existing document was kept.');}finally{setBusy('');}}
 const companies=coverage.filter(c=>(c.name+' '+c.symbols).toLowerCase().includes(companySearch.toLowerCase())&&(companyState==='all'||c.status===companyState));
 const sm=selected?matched.get(selected.id):null;
 useEffect(()=>{const mc=(navigator as any).modelContext;if(!mc?.registerTool)return;mc.registerTool({name:'search_remote_jobs',description:'Search public job listings. Does not access private documents.',inputSchema:{type:'object',properties:{query:{type:'string'},location:{type:'string'}}},execute:async({query='',location=''}:{query?:string;location?:string})=>{setFilters({...initialFilters,query,location});setTab('jobs');return {content:[{type:'text',text:JSON.stringify(filterJobs(jobs,{...initialFilters,query,location}).slice(0,20).map(j=>({title:j.title,company:j.company,location:j.location,url:j.url})))}]};}});return()=>mc.unregisterTool?.('search_remote_jobs');},[jobs]);
 return <div className="app"><header className="topbar"><a className="brand" href="#"><span className="brand-icon"><Globe2 size={23}/></span>remote<span>atlas</span></a><div className="edition">WORLDWIDE JOB SEARCH</div><button className="profile-button" onClick={()=>setTab('profile')}><FileText size={17}/>My profile{profile.length>0&&<span className="count">{profile.length}</span>}</button></header>
 <Tabs value={tab} onValueChange={setTab}><div className="nav-wrap"><TabsList variant="line" className="navigation"><TabsTrigger value="jobs"><BriefcaseBusiness/>Find a job</TabsTrigger><TabsTrigger value="profile"><FileText/>Your documents</TabsTrigger><TabsTrigger value="coverage"><Database/>Company coverage</TabsTrigger><TabsTrigger value="costs"><ChartNoAxesCombined/>Operating costs</TabsTrigger></TabsList><span className="quiet">Direct from employer career sites</span></div>
 <TabsContent value="jobs"><section className="workspace-heading"><div><p className="eyebrow">WORK BEYOND BORDERS</p><h1>Your next role.<br/><span>Wherever you call home.</span></h1><p className="subtext">Remote opportunities, with the location details that matter.</p></div><div className="catalog-note"><span className="number">{fmt(stats?.remoteJobs)}</span><span>remote roles collected</span><small>{fmt(stats?.healthyEmployers)} employers successfully checked<br/>{fmt(stats?.employerCandidates)} employers in the search registry</small></div></section>
 <form className="search-bar" onSubmit={e=>e.preventDefault()}><label className="search-field"><Search size={21}/><input aria-label="Job title, company, or keyword" placeholder="Job title, company, or keyword" value={filters.query} onChange={e=>change('query',e.target.value)}/></label><label className="search-field location"><MapPin size={21}/><input aria-label="Country, region, or city" placeholder="Country, region, or city" value={filters.location} onChange={e=>change('location',e.target.value)}/></label><button type="button" className="search-action" onClick={()=>setPage(1)}>Search jobs</button></form>
 <div className="job-layout"><aside className="filters"><div className="filter-title"><h2><SlidersHorizontal size={17}/>Refine your search</h2><button className="text-button" onClick={()=>setFilters(initialFilters)}>Reset</button></div><Pick label="Work arrangement" value={filters.remote} onChange={v=>change('remote',v)} options={['remote','hybrid','all']}/><Pick label="Experience level" value={filters.level} onChange={v=>change('level',v)} options={['all','Entry level','Mid level','Senior','Management','Senior management','Executive','Not specified']}/><Pick label="Industry" value={filters.industry} onChange={v=>change('industry',v)} options={industries}/><Pick label="Employment" value={filters.employment} onChange={v=>change('employment',v)} options={['all','Full time','Part time','Contract','Internship','Not specified']}/><div className="filter-divider"/><label className="field"><span>Salary range reaches at least</span><input type="number" min="0" placeholder="e.g. 80000" value={filters.salary} onChange={e=>change('salary',e.target.value)}/></label><div className="pair"><Pick label="Currency" value={filters.currency} onChange={v=>change('currency',v)} options={['USD','EUR','GBP','CAD','AUD','INR']}/><Pick label="Period" value={filters.interval} onChange={v=>change('interval',v)} options={['year','month','hour']}/></div><label className="check-label"><Checkbox checked={filters.disclosed} onCheckedChange={v=>change('disclosed',v===true)}/>Salary disclosed only</label><p className="fine-print">Compares the selected currency and pay period. No estimated pay or currency conversion.</p><Pick label="Found in the last (days)" value={filters.age} onChange={v=>change('age',v)} options={['all','1','7','30']}/><div className="privacy-note"><ShieldCheck size={19}/><p>Check country, work authorization, and time-zone requirements before applying.</p></div></aside>
 <section className="results"><div className="results-heading"><h2 aria-live="polite">{loading?'Loading jobs…':`${fmt(results.length)} opportunities`}</h2><Pick label="Sort" value={sort} onChange={setSort} options={['Newest','Best match']}/></div>{!profile.length?<button className="match-prompt" onClick={()=>setTab('profile')}><span className="small-icon"><FileText/></span><span><strong>Put your experience to work.</strong><small>Add your resume for skill-based suggestions.</small></span><span className="pill">Add resume</span></button>:<div className="match-active"><Check size={17}/>Documents ready. Sort by “Best match” to compare skills.</div>}
 {error&&<div className="empty"><h3>We couldn’t load the catalog</h3><p>{error}</p><button className="primary" onClick={load}>Retry</button></div>}{!loading&&!error&&!results.length&&<div className="empty"><Search size={32}/><h3>{jobs.length?'No jobs match these filters':'The first collection is in progress'}</h3><p>{jobs.length?'Try a broader location or experience level.':'Jobs appear after employer feeds are successfully collected.'}</p><button className="secondary" onClick={()=>jobs.length?setFilters(initialFilters):setTab('coverage')}>{jobs.length?'Clear filters':'View company coverage'}</button></div>}
 {results.slice((page-1)*20,page*20).map(j=><button className="job-card" key={j.id} onClick={()=>setSelected(j)}><div className="company-avatar">{j.company.split(/\s/).slice(0,2).map(w=>w[0]).join('')}</div><div className="job-main"><div className="job-kicker"><span>{j.company}</span><span>{j.industry}</span></div><h3>{j.title}</h3><div className="job-meta"><span><MapPin size={14}/>{j.location}</span><span><BriefcaseBusiness size={14}/>{j.level}</span></div><div className="job-bottom"><strong className={j.salary?'salary':'no-salary'}>{salaryLabel(j.salary)}</strong><span className="tag">{j.remoteType==='remote'?'Remote':'Hybrid'}</span>{j.worldwide&&<span className="tag">Worldwide stated</span>}{matched.get(j.id)?.available&&<span className="match-tag">{matched.get(j.id)?.score}% skill overlap</span>}</div></div><ExternalLink className="card-open" size={17}/></button>)}
 {results.length>20&&<div className="pager"><button className="secondary" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page} of {Math.ceil(results.length/20)}</span><button className="secondary" disabled={page*20>=results.length} onClick={()=>setPage(p=>p+1)}>Next</button></div>}<p className="catalog-footer"><Clock3 size={14}/>Catalog generated {when(stats?.generatedAt)}<button className="text-button" onClick={load}><RefreshCw size={14}/>Reload</button></p></section></div></TabsContent>
 <TabsContent value="profile"><section className="section-heading"><p className="eyebrow">YOUR EXPERIENCE</p><h1>Make the search yours.</h1><p>Compare your resume and cover letter with the skills mentioned in each role.</p></section><div className="privacy-banner"><ShieldCheck/><div><strong>Private on this device</strong><p>This free prototype reads documents in your browser and saves them on this device. Files never go to GitHub, employers, or an AI service. They do not sync across devices. Delete them when finished, especially on shared devices.</p></div></div><div className="document-grid">{(['resume','cover'] as const).map(kind=>{const doc=profile.find(d=>d.kind===kind);return <section className="document-card" key={kind}><FileText className="document-icon"/><h2>{kind==='resume'?'Your resume':'Your cover letter'}</h2><p>{kind==='resume'?'Skills, experience, and the work you do best.':'The interests and strengths you want to highlight.'}</p>{doc&&<div className="document-saved"><Check size={18}/><div><strong>{doc.name}</strong><small>Saved {when(doc.uploadedAt)}</small></div><button aria-label={`Delete ${kind==='resume'?'resume':'cover letter'}`} onClick={async()=>{try{await deleteDocument(kind);setProfile(await readDocuments());setMessage('Document deleted from this device.');}catch{setMessage('Unable to delete. Please retry.');}}}><Trash2 size={18}/></button></div>}<label className="upload-button"><Upload size={18}/>{busy===kind?'Reading document…':doc?'Replace document':'Choose document'}<input type="file" accept=".pdf,.docx,.txt" disabled={!!busy} onChange={e=>{upload(e.target.files?.[0],kind);e.target.value='';}}/></label><small>PDF, DOCX, or TXT · 5 MB maximum · text-based files</small></section>;})}</div><div role="status" className="message">{message}</div><section className="skills-panel"><h2>Skills found in your documents</h2>{skills.length?<div className="skill-list">{skills.map(s=><span className="tag" key={s}>{s}</span>)}</div>:<p>Add a document to see the skills used for matching.</p>}<p className="fine-print">Suggestions use a transparent vocabulary match. Skill overlap is not a hiring probability. Location and work eligibility need separate checking.</p><button className="primary" onClick={()=>{setSort('Best match');setTab('jobs');}}>See personalized suggestions</button></section><details className="paste-option"><summary>Or paste your resume text</summary><label className="field"><span>Resume text</span><textarea value={pasted} maxLength={150000} onChange={e=>setPasted(e.target.value)} rows={8}/></label><button className="secondary" disabled={pasted.trim().length<40} onClick={async()=>{try{await saveDocument({id:'resume',kind:'resume',name:'Pasted resume',text:pasted,uploadedAt:new Date().toISOString()});setProfile(await readDocuments());setPasted('');setMessage('Resume text saved privately.');}catch{setMessage('Unable to save resume text. Please retry.');}}}>Save resume text</button></details></TabsContent>
 <TabsContent value="coverage"><section className="section-heading"><p className="eyebrow">COLLECTION TRANSPARENCY</p><h1>Every company accounted for.</h1><p>Successful collections and unresolved records are shown separately.</p></section><div className="stat-grid">{[['CSV rows',stats?.inputRows],['Unique securities',stats?.uniqueSecurities],['Employer candidates',stats?.employerCandidates],['Connected employers',stats?.connectedEmployers]].map(([label,n])=><div className="stat-card" key={label}><span>{label}</span><strong>{fmt(n)}</strong></div>)}</div><div className="coverage-note"><strong>Launch target: 1,000 active remote postings.</strong><p>{fmt(stats?.remoteJobs)} collected · {fmt(stats?.csvEmployerCandidates ?? 2413)} employer candidates from your files · {fmt(stats?.addedEmployers)} additional employers researched. Passing the count threshold does not establish full coverage or subscription readiness.</p><p>{fmt(stats?.etfs)} ETFs remain in the inventory. Funds need sponsor mapping; multiple share classes are grouped conservatively. “Unresolved” means the employer has not been successfully scraped. “Partial” means more jobs may exist than were collected.</p><p>{stats?.schedule}</p></div><div className="coverage-filters"><label className="search-field"><Search size={18}/><input aria-label="Search companies or symbols" placeholder="Search companies or symbols" value={companySearch} onChange={e=>setCompanySearch(e.target.value)}/></label><Pick label="Collection status" value={companyState} onChange={setCompanyState} options={['all',...Array.from(new Set(coverage.map(c=>c.status))).sort()]}/></div><p className="fine-print">{fmt(companies.length)} records · first 100 matches shown</p><div className="table-scroll"><table><thead><tr><th>Company / fund</th><th>Status</th><th>Careers source</th><th>Last successful check</th></tr></thead><tbody>{companies.slice(0,100).map(c=><tr key={c.id}><td><strong>{c.name}</strong><small>{JSON.parse(c.symbols).join(', ')} · {c.origin==='discovered'?'Added research':'CSV source'}</small></td><td><span className={`status ${c.status}`}>{c.status.replaceAll('_',' ')}</span>{c.error&&<small>{c.error}</small>}</td><td>{c.careers_url?<a href={safeLink(c.careers_url)} target="_blank" rel="noreferrer">{c.adapter||'Careers page'} <ExternalLink size={13}/></a>:c.website?<a href={safeLink(c.website)} target="_blank" rel="noreferrer">Company website</a>:'Not yet verified'}</td><td>{when(c.last_success)}</td></tr>)}</tbody></table></div></TabsContent>
 <TabsContent value="costs"><CostView employers={stats?.employerCandidates||2413}/></TabsContent></Tabs><footer className="site-footer"><span>remoteatlas</span><p>Free research prototype. Verify details with the employer. Missing salary and eligibility information is never invented.</p></footer>
 <Sheet open={!!selected} onOpenChange={open=>{if(!open)setSelected(null);}}><SheetContent className="job-detail">{selected&&<><div className="detail-head"><p className="eyebrow">{selected.company}</p><SheetTitle>{selected.title}</SheetTitle><SheetDescription>{selected.location}</SheetDescription><div className="skill-list"><span className="tag">{selected.remoteType}</span><span className="tag">{selected.level}</span></div><strong className="detail-salary">{salaryLabel(selected.salary)}</strong><a className="primary apply" href={safeLink(selected.url)} target="_blank" rel="noreferrer">View employer posting <ExternalLink size={17}/></a></div><div className="detail-body"><section><h3>Location & eligibility</h3><p>{selected.location}</p><p>{selected.worldwide?'Employer explicitly lists worldwide availability.':selected.countries.length?`Countries mentioned: ${selected.countries.join(', ')}.`:'Country eligibility is not specified. Remote does not mean worldwide.'}</p>{selected.restrictions.map((r,i)=><p className="restriction" key={i}>{r}</p>)}<small>Remote evidence: {selected.remoteEvidence}</small></section>{sm?.available&&<section className="match-section"><h3>{sm.score}% skill overlap</h3><p>{sm.shared.length?'Shared skills: '+sm.shared.join(', '):'No shared skills found in the matching vocabulary.'}</p>{sm.missing.length>0&&<p>Review these requirements: {sm.missing.join(', ')}.</p>}<small>Highlight relevant experience. Only claim skills you actually have.</small></section>}<section><h3>Job description</h3><div className="description">{selected.description||'View the employer posting for the description.'}</div></section><section className="detail-metadata"><p>Industry: {selected.industry}</p><p>Employment: {selected.employmentType}</p><p>Level: {selected.levelSource}</p><p>First collected: {when(selected.firstSeen)}</p><p>Last checked: {when(selected.lastSeen)}</p>{selected.salary?.evidence&&<p>Salary source: {selected.salary.evidence}</p>}</section></div></>}</SheetContent></Sheet></div>;
}
