"use client";
import {useState} from 'react';
import {costs,MONTHLY_PRICE,ANNUAL_PRICE,type Channel,type Billing} from '../lib/cost-model';
export default function CostView({employers}:{employers:number}){
 const [users,setUsers]=useState(1000),[minutes,setMinutes]=useState(90),[maintenance,setMaintenance]=useState(16),[iosHours,setIosHours]=useState(6);
 const [channel,setChannel]=useState<Channel>('ios15'),[billing,setBilling]=useState<Billing>('monthly'),[privateRunner,setPrivateRunner]=useState(false);
 const m=costs({users,minutes,maintenance,iosHours,channel,billing,privateRunner});
 return <><section className="section-heading"><p className="eyebrow">OCTOBER 1, 2026 · USD · iOS LAUNCH MODEL</p><h1>The economics of a daily search.</h1><p>One shared catalog for web and iOS. At least 1,000 active remote postings before considering paid launch; {employers.toLocaleString()} employers currently in the search registry.</p></section>
 <div className="cost-layout"><section className="cost-inputs"><h2>Adjust the assumptions</h2>
 <label className="field"><span>Payment channel</span><select value={channel} onChange={e=>setChannel(e.target.value as Channel)}><option value="ios15">iOS · Apple 15% (eligible / enrolled)</option><option value="ios30">iOS · Apple 30% sensitivity</option><option value="web">Web · Stripe 3.6% + $0.30</option></select></label>
 <label className="field"><span>Subscription mix</span><select value={billing} onChange={e=>setBilling(e.target.value as Billing)}><option value="monthly">All monthly</option><option value="annual">All annual</option><option value="mixed">50% monthly / 50% annual</option></select></label>
 {([['Paying subscribers',users,setUsers],['Runner minutes / day',minutes,setMinutes],['Core maintenance hours / month',maintenance,setMaintenance],...(channel==='web'?[]:[['Additional iOS hours / month',iosHours,setIosHours]])] as [string,number,(n:number)=>void][]).map(([label,value,set])=><label className="field" key={label}><span>{label}</span><input type="number" min="0" value={value} onChange={e=>set(Math.max(0,+e.target.value))}/></label>)}
 <label className="check-field"><input type="checkbox" checked={privateRunner} onChange={e=>setPrivateRunner(e.target.checked)}/> Model a private GitHub Free repository</label>
 <p className="fine-print">Public standard runners have no minute charge. Private pricing assumes all 2,000 included minutes are available. Labor at $75/hour is an estimate. Apple membership is shared across your apps; an existing membership may add no incremental fee.</p></section>
 <section className="cost-summary"><div className="cost-total"><span>Monthly operating budget</span><strong>${Math.round(m.total).toLocaleString()}</strong><small>Includes platform fees and modeled maintenance; excludes marketing, tax, and initial development</small></div><table><tbody>{[['Daily crawler compute',m.crawl],['App hosting',5],['Database, auth & private storage',25],['Email allowance',20],['Monitoring & backups',20],['Domain allowance',2],['Collection contingency',40],['Variable service reserve',m.variable],['Core maintenance',m.coreLabor],['Additional iOS maintenance',m.iosLabor],['Apple membership allocation',m.apple],['Payment / platform fees',m.fees]].map(([label,amount])=><tr key={label}><td>{label}</td><td>${Number(amount).toFixed(2)}</td></tr>)}</tbody></table><p className="fine-print">Revenue at this mix: ${m.revenue.toLocaleString(undefined,{maximumFractionDigits:2})}/month equivalent. Annual cash is collected up front.</p></section></div>
 <div className="pricing-recommendation"><div><p className="eyebrow">RECOMMENDED LAUNCH PRICE</p><h2>${MONTHLY_PRICE}<small>/ month</small></h2><p>Or <strong>${ANNUAL_PRICE} / year</strong> (${(ANNUAL_PRICE/12).toFixed(2)} monthly equivalent, {Math.round((1-ANNUAL_PRICE/(MONTHLY_PRICE*12))*100)}% off).</p></div><div><strong>{m.breakEven} paying subscribers</strong><p>Modeled break-even for the selected platform and billing mix. iOS purchases incur Apple’s commission; Stripe is not added to those transactions.</p></div></div>
 <p className="coverage-note">The prototype is free. A paid iOS release needs reliable daily collection, native app features, StoreKit subscriptions, and a production backend. Reaching 1,000 postings is a minimum count, not proof of customer value. Apple’s 15% rate requires eligibility and enrollment; otherwise new subscriptions generally use the 30% scenario, falling to 15% after one paid year. Taxes and storefront-specific terms can change proceeds.</p>
 <div className="source-links"><h2>Price sources & assumptions</h2>{[['Apple membership','https://developer.apple.com/programs/whats-included/'],['Apple Small Business Program','https://developer.apple.com/app-store/small-business-program/'],['Apple subscriptions','https://developer.apple.com/app-store/subscriptions/'],['GitHub Actions','https://docs.github.com/en/billing/concepts/product-billing/github-actions'],['Cloudflare','https://developers.cloudflare.com/workers/platform/pricing/'],['Supabase','https://supabase.com/pricing'],['Stripe','https://stripe.com/pricing']].map(([label,url])=><a key={label} href={url} target="_blank" rel="noreferrer">{label}</a>)}</div></>;
}
