"use client";
import {useState} from 'react';
import {costs,MONTHLY_PRICE,ANNUAL_PRICE,type Channel,type Billing,type Product} from '../lib/cost-model';
export default function CostView({employers}:{employers:number}){
 const [users,setUsers]=useState(1000),[minutes,setMinutes]=useState(90),[maintenance,setMaintenance]=useState(12),[marketing,setMarketing]=useState(0),[webHours,setWebHours]=useState(4),[iosHours,setIosHours]=useState(6);
 const [product,setProduct]=useState<Product>('ios-only'),[channel,setChannel]=useState<Channel>('ios15'),[billing,setBilling]=useState<Billing>('monthly'),[privateRunner,setPrivateRunner]=useState(false);
 const assumptions={users,minutes,maintenance,marketing,webHours,iosHours,channel,billing,privateRunner};
 const m=costs({...assumptions,product});
 const money=(n:number)=>n.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
 return <><section className="section-heading"><p className="eyebrow">OCTOBER 1, 2026 · USD · iOS-ONLY & MULTIPLATFORM</p><h1>The economics of a daily search.</h1><p>An iOS-only launch still needs the shared crawler, catalog API and private backend. At least 1,000 active remote postings before considering paid launch; {employers.toLocaleString()} employers currently in the search registry.</p></section>
 <div className="cost-layout"><section className="cost-inputs"><h2>Adjust the assumptions</h2>
 <label className="field"><span>Product scope</span><select aria-label="Product scope" value={product} onChange={e=>setProduct(e.target.value as Product)}><option value="ios-only">iOS app only</option><option value="web-ios">Web app + iOS app</option><option value="web-only">Web app only</option></select></label>
 {product!=='web-only'?<label className="field"><span>Apple commission</span><select aria-label="Apple commission" value={channel} onChange={e=>setChannel(e.target.value as Channel)}><option value="ios15">15% · eligible and enrolled</option><option value="ios30">30% · first-year sensitivity</option></select></label>:<p className="fine-print">Web purchases use Stripe at 3.6% + $0.30 per transaction, including the modeled Billing fee.</p>}
 <label className="field"><span>Subscription mix</span><select aria-label="Subscription mix" value={billing} onChange={e=>setBilling(e.target.value as Billing)}><option value="monthly">All monthly</option><option value="annual">All annual</option><option value="mixed">50% monthly / 50% annual</option></select></label>
 {([['Paying subscribers',users,setUsers],['Runner minutes / day',minutes,setMinutes],['Marketing budget / month',marketing,setMarketing],['Crawler & backend hours / month',maintenance,setMaintenance],...(product==='ios-only'?[]:[['Web app hours / month',webHours,setWebHours]]),...(product==='web-only'?[]:[['iOS app hours / month',iosHours,setIosHours]])] as [string,number,(n:number)=>void][]).map(([label,value,set])=><label className="field" key={label}><span>{label}</span><input aria-label={label} type="number" min="0" value={value} onChange={e=>set(Math.max(0,+e.target.value))}/></label>)}
 <label className="check-field"><input type="checkbox" checked={privateRunner} onChange={e=>setPrivateRunner(e.target.checked)}/> Model a private GitHub Free repository</label>
 <p className="fine-print">Public standard runners have no minute charge. Private pricing assumes all 2,000 included minutes are available. Labor at $75/hour is an estimate. Apple membership is shared across your apps; an existing membership may add no incremental fee.</p></section>
 <section className="cost-summary"><div className="cost-total"><span>Monthly operating budget</span><strong>${Math.round(m.total).toLocaleString()}</strong><small>${money(m.total*12)} per year at steady usage. Includes platform fees and modeled maintenance; includes your marketing budget; excludes tax and initial development.</small></div><table><tbody>{[['Daily crawler compute',m.crawl],['Backend / API hosting',5],['Database, auth & private storage',25],['Email allowance',20],['Monitoring & backups',20],['Domain allowance',2],['Collection contingency',40],['Variable service reserve',m.variable],['Crawler & backend maintenance',m.coreLabor],['Web app maintenance',m.webLabor],['iOS app maintenance',m.iosLabor],['Apple membership allocation',m.apple],['Payment / platform fees',m.fees],['Marketing & acquisition',m.marketing]].map(([label,amount])=><tr key={label}><td>{label}</td><td>${Number(amount).toFixed(2)}</td></tr>)}</tbody></table><p className="fine-print">Revenue at this mix: ${money(m.revenue)}/month equivalent. Annual cash is collected up front. Services and reserves before labor and platform fees: ${money(m.infrastructure+m.apple+m.variable)}/month.</p></section></div>
 <section className="cost-summary profit-summary"><p className="eyebrow">PROJECTED OPERATING PROFIT</p><h2>${money(m.profit)} / month</h2><p><strong>${money(m.annualProfit)} / year</strong> at steady subscriber count{m.profitMargin===null?'':` · ${(m.profitMargin*100).toFixed(1)}% operating margin`}.</p><p className="fine-print">Revenue minus the operating budget above, including maintenance labor, reserves, payment fees and the selected marketing budget. A negative figure is a loss. This is a subscriber scenario, not a demand forecast. Marketing starts at $0; enter a budget to include acquisition costs. Excludes tax, refunds, initial development and owner compensation beyond modeled maintenance.</p></section>
 <div className="pricing-recommendation"><div><p className="eyebrow">RECOMMENDED LAUNCH PRICE</p><h2>${MONTHLY_PRICE}<small>/ month</small></h2><p>Or <strong>${ANNUAL_PRICE} / year</strong> (${(ANNUAL_PRICE/12).toFixed(2)} monthly equivalent, {Math.round((1-ANNUAL_PRICE/(MONTHLY_PRICE*12))*100)}% off).</p></div><div><strong>{m.breakEven} paying subscribers</strong><p>Modeled break-even for the selected product and billing mix. iOS purchases incur Apple’s commission; Stripe is not added to those transactions.</p></div></div>
 <section className="cost-summary cost-comparison"><h2>iOS only compared with other launch options</h2><p className="fine-print">Uses your subscriber count, billing mix and maintenance assumptions. Both iOS scenarios assume all purchases go through Apple. A free marketing/support page is included in backend hosting; iOS only has no maintained customer web app.</p><table><thead><tr><th>Product</th><th>Monthly</th><th>Yearly cost</th><th>Profit / month</th><th>Profit / year</th><th>Break-even</th></tr></thead><tbody>{([['ios-only','iOS app only'],['web-ios','Web + iOS'],['web-only','Web app only']] as [Product,string][]).map(([p,label])=>{const c=costs({...assumptions,product:p});return <tr key={p}><td>{label}</td><td>${money(c.total)}</td><td>${money(c.total*12)}</td><td>${money(c.profit)}</td><td>${money(c.annualProfit)}</td><td>{c.breakEven} subscribers</td></tr>})}</tbody></table><p className="fine-print">Initial engineering allowance: iOS only $13,500–$30,000; web + iOS $15,000–$34,500; web only $9,000–$22,500. These estimate work remaining after the prototype at $75/hour. They exclude hardware, marketing, licensed data and legal review; they are not amounts spent.</p></section>
 <section className="cost-summary cost-comparison"><h2>Profit at different subscriber counts</h2><p className="fine-print">Uses the selected product, billing mix and commission. These fixed-cost scenarios hold each subscriber count steady for a year; growth, churn and larger support teams are not modeled.</p><table><thead><tr><th>Subscribers</th><th>Revenue / month</th><th>Cost / month</th><th>Profit / month</th><th>Profit / year</th></tr></thead><tbody>{[100,250,500,1000].map(n=>{const c=costs({...assumptions,product,users:n});return <tr key={n}><td>{n.toLocaleString()}</td><td>${money(c.revenue)}</td><td>${money(c.total)}</td><td>${money(c.profit)}</td><td>${money(c.annualProfit)}</td></tr>})}</tbody></table></section>
 <p className="coverage-note">The prototype is free. A paid iOS release needs reliable daily collection, native app features, StoreKit subscriptions, and a production backend. Reaching 1,000 postings is a minimum count, not proof of customer value. Apple’s 15% rate requires eligibility and enrollment; otherwise new subscriptions generally use the 30% scenario, falling to 15% after one paid year. Taxes and storefront-specific terms can change proceeds.</p>
 <div className="source-links"><h2>Price sources & assumptions</h2>{[['Apple membership','https://developer.apple.com/programs/whats-included/'],['Apple Small Business Program','https://developer.apple.com/app-store/small-business-program/'],['Apple subscriptions','https://developer.apple.com/app-store/subscriptions/'],['GitHub Actions','https://docs.github.com/en/billing/concepts/product-billing/github-actions'],['Cloudflare','https://developers.cloudflare.com/workers/platform/pricing/'],['Supabase','https://supabase.com/pricing'],['Stripe','https://stripe.com/pricing']].map(([label,url])=><a key={label} href={url} target="_blank" rel="noreferrer">{label}</a>)}</div></>;
}
