import assert from 'node:assert/strict';
import {costs} from '../lib/cost-model.ts';
const small=costs();
assert.equal(small.breakEven,141);
assert.equal(small.total,4118.75);
assert.equal(small.fees,2248.5);
assert.equal(costs({channel:'ios30'}).breakEven,171);
assert.equal(costs({channel:'ios15',billing:'annual'}).breakEven,211);
assert.ok(Math.abs(costs({channel:'web',billing:'annual',users:1}).fees-(119.99*.036+.3)/12)<1e-9);
assert.equal(costs({privateRunner:true}).crawl,4.2);
assert.equal(costs({channel:'web'}).apple,0);
assert.equal(costs({channel:'web'}).iosLabor,0);
const iosOnly=costs({product:'ios-only'});
assert.equal(iosOnly.total,3818.75);
assert.equal(iosOnly.fixed,1470.25);
assert.equal(iosOnly.breakEven,117);
assert.equal(iosOnly.webLabor,0);
assert.equal(small.total-iosOnly.total,300);
assert.equal(costs({product:'ios-only',channel:'ios30'}).breakEven,142);
assert.equal(costs({product:'ios-only',billing:'annual'}).breakEven,176);
assert.equal(costs({product:'ios-only',channel:'ios30',billing:'annual'}).breakEven,214);
assert.equal(costs({product:'web-only',channel:'ios30'}).fees,costs({channel:'web'}).fees);
assert.equal(costs({product:'ios-only',maintenance:0,iosHours:0}).total-iosOnly.fees,220.25);
assert.equal(iosOnly.profit,11171.25);
assert.equal(costs({product:'ios-only',marketing:500}).profit,iosOnly.profit-500);
assert.ok(costs({product:'ios-only',marketing:500}).breakEven>iosOnly.breakEven);
assert.equal(iosOnly.annualProfit,134055);
assert.ok(costs({product:'ios-only',users:100}).profit<0);
assert.equal(costs({product:'ios-only',users:0}).profit,-1470.25);
assert.equal(costs({users:0}).profitMargin,null);
assert.equal(costs({product:'ios-only',users:iosOnly.breakEven}).profit>=0,true);
assert.equal(costs({product:'ios-only',users:iosOnly.breakEven-1}).profit<0,true);
console.log('Cost scenarios passed: iOS-only and combined scope, Apple 15%/30%, annual billing, web fees, shared runner allowance.');
